#############################################################################
# Makefile for building: libTimelineView.1.0.0.dylib
# Generated by qmake (3.0) (Qt 5.4.1)
# Project:  TimelineView.pro
# Template: lib
# Command: /Users/admin/Qt5.4.1/5.4/clang_64/bin/qmake -spec macx-xcode -o TimelineView.xcodeproj/project.pbxproj TimelineView.pro
#############################################################################

MAKEFILE      = project.pbxproj

MOC       = /Users/admin/Qt5.4.1/5.4/clang_64/bin/moc
UIC       = 
LEX       = flex
LEXFLAGS  = 
YACC      = yacc
YACCFLAGS = -d
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
INCPATH       = -I. -I. -ITimelineManager -ITools -I../../../../Qt5.4.1/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers -I../../../../Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/AGL.framework/Headers -I../../../../Qt5.4.1/5.4/clang_64/mkspecs/macx-clang -F/Users/admin/Qt5.4.1/5.4/clang_64/lib
DEL_FILE  = rm -f
MOVE      = mv -f

IMAGES = 
PARSERS =
preprocess: $(PARSERS) compilers
clean preprocess_clean: parser_clean compiler_clean

parser_clean:
mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compilers: qrc_timelineview.cpp moc_timelineviewtrack.cpp moc_timelinecommon.cpp moc_timelineviewprivate.cpp\
	 moc_ClipBase.cpp moc_Command.cpp moc_ComplexClipController.cpp\
	 moc_ThumbnailExtractHelper.cpp moc_ThumbnailExtractor.cpp moc_TimelineManager.cpp\
	 moc_TrackBase.cpp moc_TrackManager.cpp moc_MediaCropDialog.cpp
compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all: qrc_timelineview.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_timelineview.cpp
qrc_timelineview.cpp: timelineview.qrc \
		Resources/styles.qss \
		Resources/normal/TimelineView_Redo_n.png \
		Resources/normal/TimelineView_Crop_d.png \
		Resources/normal/TimelineView_Crop_h.png \
		Resources/normal/TimelineView_Delete_d.png \
		Resources/normal/TimelineView_Header_Video_n.png \
		Resources/normal/TimelineView_Undo_d.png \
		Resources/normal/TimelineView_Zoom_Track_bg.png \
		Resources/normal/TimelineView_Delete_h.png \
		Resources/normal/TimelineView_Cut_d.png \
		Resources/normal/TimelineView_Crop_n.png \
		Resources/normal/TimelineView_Undo_h.png \
		Resources/normal/TimelineView_Cut_h.png \
		Resources/normal/TimelineView_Delete_n.png \
		Resources/normal/TimelineView_Undo_n.png \
		Resources/normal/TimelineView_TrackSet_d.png \
		Resources/normal/TimelineView_Header_Audio_n.png \
		Resources/normal/TimelineView_Header_Effect_n.png \
		Resources/normal/TimelineView_Zoom_chunk.png \
		Resources/normal/TimelineView_Cut_n.png \
		Resources/normal/TimelineView_TrackSet_h.png \
		Resources/normal/TimelineView_Redo_d.png \
		Resources/normal/TimelineView_TextEdit_h.png \
		Resources/normal/TimelineView_Redo_h.png \
		Resources/normal/TimelineView_TrackSet_n.png \
		Resources/normal/TimelineView_TextEdit_n.png \
		Resources/normal/TimelineView_Zoom_Track_groove.png
	/Users/admin/Qt5.4.1/5.4/clang_64/bin/rcc -name timelineview timelineview.qrc -o qrc_timelineview.cpp

compiler_moc_header_make_all: moc_timelineviewtrack.cpp moc_timelinecommon.cpp moc_timelineviewprivate.cpp moc_ClipBase.cpp moc_Command.cpp moc_ComplexClipController.cpp moc_ThumbnailExtractHelper.cpp moc_ThumbnailExtractor.cpp moc_TimelineManager.cpp moc_TrackBase.cpp moc_TrackManager.cpp moc_MediaCropDialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_timelineviewtrack.cpp moc_timelinecommon.cpp moc_timelineviewprivate.cpp moc_ClipBase.cpp moc_Command.cpp moc_ComplexClipController.cpp moc_ThumbnailExtractHelper.cpp moc_ThumbnailExtractor.cpp moc_TimelineManager.cpp moc_TrackBase.cpp moc_TrackManager.cpp moc_MediaCropDialog.cpp
moc_timelineviewtrack.cpp: timelinecommon.h \
		timelineviewtrack.h
	/Users/admin/Qt5.4.1/5.4/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/admin/Qt5.4.1/5.4/clang_64/mkspecs/macx-clang -I/Users/admin/Documents/project/NLEPreview/TimelineView -I/Users/admin/Documents/project/NLEPreview/TimelineView -I/Users/admin/Documents/project/NLEPreview/TimelineView/TimelineManager -I/Users/admin/Documents/project/NLEPreview/TimelineView/Tools -I/Users/admin/Qt5.4.1/5.4/clang_64/lib/QtGui.framework/Headers -I/Users/admin/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Headers -F/Users/admin/Qt5.4.1/5.4/clang_64/lib timelineviewtrack.h -o moc_timelineviewtrack.cpp

moc_timelinecommon.cpp: timelinecommon.h
	/Users/admin/Qt5.4.1/5.4/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/admin/Qt5.4.1/5.4/clang_64/mkspecs/macx-clang -I/Users/admin/Documents/project/NLEPreview/TimelineView -I/Users/admin/Documents/project/NLEPreview/TimelineView -I/Users/admin/Documents/project/NLEPreview/TimelineView/TimelineManager -I/Users/admin/Documents/project/NLEPreview/TimelineView/Tools -I/Users/admin/Qt5.4.1/5.4/clang_64/lib/QtGui.framework/Headers -I/Users/admin/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Headers -F/Users/admin/Qt5.4.1/5.4/clang_64/lib timelinecommon.h -o moc_timelinecommon.cpp

moc_timelineviewprivate.cpp: timelineviewprivate.h
	/Users/admin/Qt5.4.1/5.4/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/admin/Qt5.4.1/5.4/clang_64/mkspecs/macx-clang -I/Users/admin/Documents/project/NLEPreview/TimelineView -I/Users/admin/Documents/project/NLEPreview/TimelineView -I/Users/admin/Documents/project/NLEPreview/TimelineView/TimelineManager -I/Users/admin/Documents/project/NLEPreview/TimelineView/Tools -I/Users/admin/Qt5.4.1/5.4/clang_64/lib/QtGui.framework/Headers -I/Users/admin/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Headers -F/Users/admin/Qt5.4.1/5.4/clang_64/lib timelineviewprivate.h -o moc_timelineviewprivate.cpp

moc_ClipBase.cpp: ../../../../Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../../Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QSize \
		TimelineManager/ClipBase.h
	/Users/admin/Qt5.4.1/5.4/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/admin/Qt5.4.1/5.4/clang_64/mkspecs/macx-clang -I/Users/admin/Documents/project/NLEPreview/TimelineView -I/Users/admin/Documents/project/NLEPreview/TimelineView -I/Users/admin/Documents/project/NLEPreview/TimelineView/TimelineManager -I/Users/admin/Documents/project/NLEPreview/TimelineView/Tools -I/Users/admin/Qt5.4.1/5.4/clang_64/lib/QtGui.framework/Headers -I/Users/admin/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Headers -F/Users/admin/Qt5.4.1/5.4/clang_64/lib TimelineManager/ClipBase.h -o moc_ClipBase.cpp

moc_Command.cpp: TimelineManager/Command.h
	/Users/admin/Qt5.4.1/5.4/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/admin/Qt5.4.1/5.4/clang_64/mkspecs/macx-clang -I/Users/admin/Documents/project/NLEPreview/TimelineView -I/Users/admin/Documents/project/NLEPreview/TimelineView -I/Users/admin/Documents/project/NLEPreview/TimelineView/TimelineManager -I/Users/admin/Documents/project/NLEPreview/TimelineView/Tools -I/Users/admin/Qt5.4.1/5.4/clang_64/lib/QtGui.framework/Headers -I/Users/admin/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Headers -F/Users/admin/Qt5.4.1/5.4/clang_64/lib TimelineManager/Command.h -o moc_Command.cpp

moc_ComplexClipController.cpp: ../../../../Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		TimelineManager/ComplexClipController.h
	/Users/admin/Qt5.4.1/5.4/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/admin/Qt5.4.1/5.4/clang_64/mkspecs/macx-clang -I/Users/admin/Documents/project/NLEPreview/TimelineView -I/Users/admin/Documents/project/NLEPreview/TimelineView -I/Users/admin/Documents/project/NLEPreview/TimelineView/TimelineManager -I/Users/admin/Documents/project/NLEPreview/TimelineView/Tools -I/Users/admin/Qt5.4.1/5.4/clang_64/lib/QtGui.framework/Headers -I/Users/admin/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Headers -F/Users/admin/Qt5.4.1/5.4/clang_64/lib TimelineManager/ComplexClipController.h -o moc_ComplexClipController.cpp

moc_ThumbnailExtractHelper.cpp: ../../../../Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		TimelineManager/ThumbnailExtractHelper.h
	/Users/admin/Qt5.4.1/5.4/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/admin/Qt5.4.1/5.4/clang_64/mkspecs/macx-clang -I/Users/admin/Documents/project/NLEPreview/TimelineView -I/Users/admin/Documents/project/NLEPreview/TimelineView -I/Users/admin/Documents/project/NLEPreview/TimelineView/TimelineManager -I/Users/admin/Documents/project/NLEPreview/TimelineView/Tools -I/Users/admin/Qt5.4.1/5.4/clang_64/lib/QtGui.framework/Headers -I/Users/admin/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Headers -F/Users/admin/Qt5.4.1/5.4/clang_64/lib TimelineManager/ThumbnailExtractHelper.h -o moc_ThumbnailExtractHelper.cpp

moc_ThumbnailExtractor.cpp: ../../../../Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../../Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QThread \
		TimelineManager/ThumbnailExtractor.h
	/Users/admin/Qt5.4.1/5.4/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/admin/Qt5.4.1/5.4/clang_64/mkspecs/macx-clang -I/Users/admin/Documents/project/NLEPreview/TimelineView -I/Users/admin/Documents/project/NLEPreview/TimelineView -I/Users/admin/Documents/project/NLEPreview/TimelineView/TimelineManager -I/Users/admin/Documents/project/NLEPreview/TimelineView/Tools -I/Users/admin/Qt5.4.1/5.4/clang_64/lib/QtGui.framework/Headers -I/Users/admin/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Headers -F/Users/admin/Qt5.4.1/5.4/clang_64/lib TimelineManager/ThumbnailExtractor.h -o moc_ThumbnailExtractor.cpp

moc_TimelineManager.cpp: ../../../../Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../../Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QStack \
		../../../../Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QPoint \
		TimelineManager/TimelineManager.h
	/Users/admin/Qt5.4.1/5.4/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/admin/Qt5.4.1/5.4/clang_64/mkspecs/macx-clang -I/Users/admin/Documents/project/NLEPreview/TimelineView -I/Users/admin/Documents/project/NLEPreview/TimelineView -I/Users/admin/Documents/project/NLEPreview/TimelineView/TimelineManager -I/Users/admin/Documents/project/NLEPreview/TimelineView/Tools -I/Users/admin/Qt5.4.1/5.4/clang_64/lib/QtGui.framework/Headers -I/Users/admin/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Headers -F/Users/admin/Qt5.4.1/5.4/clang_64/lib TimelineManager/TimelineManager.h -o moc_TimelineManager.cpp

moc_TrackBase.cpp: ../../../../Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../../Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QVector \
		../../../../Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QMap \
		TimelineManager/TypeDefine.h \
		../../../../Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		TimelineManager/TrackBase.h
	/Users/admin/Qt5.4.1/5.4/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/admin/Qt5.4.1/5.4/clang_64/mkspecs/macx-clang -I/Users/admin/Documents/project/NLEPreview/TimelineView -I/Users/admin/Documents/project/NLEPreview/TimelineView -I/Users/admin/Documents/project/NLEPreview/TimelineView/TimelineManager -I/Users/admin/Documents/project/NLEPreview/TimelineView/Tools -I/Users/admin/Qt5.4.1/5.4/clang_64/lib/QtGui.framework/Headers -I/Users/admin/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Headers -F/Users/admin/Qt5.4.1/5.4/clang_64/lib TimelineManager/TrackBase.h -o moc_TrackBase.cpp

moc_TrackManager.cpp: ../../../../Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../../Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QVector \
		TimelineManager/TrackBase.h \
		../../../../Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QMap \
		TimelineManager/TypeDefine.h \
		../../../../Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		TimelineManager/TrackManager.h
	/Users/admin/Qt5.4.1/5.4/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/admin/Qt5.4.1/5.4/clang_64/mkspecs/macx-clang -I/Users/admin/Documents/project/NLEPreview/TimelineView -I/Users/admin/Documents/project/NLEPreview/TimelineView -I/Users/admin/Documents/project/NLEPreview/TimelineView/TimelineManager -I/Users/admin/Documents/project/NLEPreview/TimelineView/Tools -I/Users/admin/Qt5.4.1/5.4/clang_64/lib/QtGui.framework/Headers -I/Users/admin/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Headers -F/Users/admin/Qt5.4.1/5.4/clang_64/lib TimelineManager/TrackManager.h -o moc_TrackManager.cpp

moc_MediaCropDialog.cpp: Tools/MediaCropDialog.h
	/Users/admin/Qt5.4.1/5.4/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/admin/Qt5.4.1/5.4/clang_64/mkspecs/macx-clang -I/Users/admin/Documents/project/NLEPreview/TimelineView -I/Users/admin/Documents/project/NLEPreview/TimelineView -I/Users/admin/Documents/project/NLEPreview/TimelineView/TimelineManager -I/Users/admin/Documents/project/NLEPreview/TimelineView/Tools -I/Users/admin/Qt5.4.1/5.4/clang_64/lib/QtGui.framework/Headers -I/Users/admin/Qt5.4.1/5.4/clang_64/lib/QtCore.framework/Headers -F/Users/admin/Qt5.4.1/5.4/clang_64/lib Tools/MediaCropDialog.h -o moc_MediaCropDialog.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean 

